FROM --platform=${BUILDPLATFORM} golang:alpine AS build

WORKDIR /src
ENV CGO_ENABLED=0
COPY docker/usdt/src .
ARG TARGETOS
ARG TARGETARCH
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/epusdt .

FROM alpine
LABEL maintainer="sudo@reea.dev"

WORKDIR /usdt
COPY --from=build /out/epusdt /usdt/epusdt
COPY --from=build /src/static /usdt/static
RUN set -xe \
    && chmod +x /usdt/epusdt

CMD /usdt/epusdt http start
